const $ = id => document.getElementById(id);
let lastFrame = -1;
const labels={loading:'加载中',ready:'就绪',healthy:'正常',waiting:'等待',confirmed:'已确认',failed:'失败',safe:'安全',attention:'注意',high:'高风险',critical:'严重风险',fault:'故障',vented:'已泄压',inflating:'充气中',holding:'保持中',venting:'泄压中'};
const text=v=>labels[v]||v||'等待';
async function api(path, options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function eventOf(events,key){return events[key]||{}}
function setStatus(textValue,tone='waiting'){const e=$('system-status');e.textContent=textValue;e.className=`pill ${tone}`}
function render(s){const chain=s.chain||{},upload=chain.upload||{},model=chain.model||{},callback=chain.callback||{},risk=chain.risk||{},action=chain.action||{},events=s.events||{},serial=s.serial||{};
 const serialText=serial.confirmed?`● ${serial.port} 已确认`:(serial.open?`● ${serial.port} 等待遥测`:'● 设备未连接');$('device-toggle').textContent=serialText;$('serial-detail').textContent=serial.error|| (serial.confirmed?'已收到真实 AIX 遥测。':'端口打开不代表设备已连接。');
 const fault=action.state==='fault'||s.chain_error;setStatus(fault?'闭环异常':callback.state==='confirmed'?'闭环运行正常':'链路连接中',fault?'fault':callback.state==='confirmed'?'ok':'waiting');
 const score=risk.valid&&!fault?String(risk.score??'--').padStart(2,'0'):'--';$('risk-score').textContent=score;$('risk-band').textContent=fault?'结果失效':text(risk.band);$('risk-reason').textContent=risk.reason||model.error||s.chain_error||'等待真实风险结果。';
 $('frame-label').textContent=chain.display?.ready?`第 ${chain.display.frame_seq} 帧`:'等待首帧';$('upload-stage').textContent=`${text(upload.state)} · ${Number(upload.fps||0).toFixed(2)} FPS`;$('model-stage').textContent=`${text(model.state)} · ${model.latency_ms??'--'} ms`;$('callback-stage').textContent=`${text(callback.state)} · ${action.state||'等待'}`;$('action-ack').textContent=action.confirmed?`第 ${action.frame_seq} 帧真实确认`:'等待 ESP32 动作确认';$('e2e-latency').textContent=action.e2e_latency_ms!=null?`${action.e2e_latency_ms} ms`:'--';
 const pressure=eventOf(events,'pressure'), camera=eventOf(events,'camerastatus'), motion=eventOf(events,'motion'), pneumatic=eventOf(events,'pneumaticstatus'), voice=eventOf(events,'voicestatus'), hardware=eventOf(events,'hardwarehealth');
 $('camera-metric').textContent=camera.sensor?`${camera.sensor} · ${Number(camera.fps||0).toFixed(2)} FPS`:'等待设备遥测';$('pressure-metric').textContent=pressure.filtered_kpa!=null?`${Number(pressure.filtered_kpa).toFixed(2)} kPa · ${pressure.valid?'有效':'无效'}`:'--';$('motion-metric').textContent=motion.calibrated?`已校准 · 冲击 ${motion.impact?'是':'否'}`:'等待设备遥测';$('pneumatic-metric').textContent=pneumatic.state?`${text(pneumatic.state)} · 泵${pneumatic.pump_on?'开':'关'} · 阀${pneumatic.valve_on?'通电':'断电'}`:'等待设备遥测';$('voice-metric').textContent=voice.state?`${voice.state} · 音轨 ${voice.track??'--'}`:'等待设备遥测';$('hardware-metric').textContent=hardware.overall?`${text(hardware.overall)} · 自动${hardware.automatic_ready?'允许':'禁止'}`:'等待设备遥测';
 $('scenario-camera').textContent=`${text(upload.state)} / ${Number(upload.fps||0).toFixed(2)} FPS`;$('scenario-model').textContent=`${text(model.state)} / ${model.latency_ms??'--'} ms`;$('scenario-action').textContent=action.confirmed?`${text(action.state)} / 已确认`:'等待 ESP32 确认';$('chain-error').textContent=s.chain_error||'';$('protocol-log').textContent=(s.logs||[]).slice(-40).join('\n')||'等待遥测…';
 const frame=chain.display?.frame_seq;if(chain.display?.ready&&frame!==lastFrame){lastFrame=frame;$('snapshot').src=`/api/snapshot?t=${Date.now()}`;$('snapshot-empty').hidden=true;}
}
async function refreshPorts(){try{const d=await api('/api/ports');const select=$('port-select');select.innerHTML=d.ports.map(p=>`<option value="${p.device}">${p.device} — ${p.description}</option>`).join('')||'<option value="">未发现串口</option>'}catch(e){$('serial-detail').textContent=e.message}}
async function poll(){try{render(await api('/api/state'))}catch(e){setStatus('网页服务异常','fault');$('chain-error').textContent=e.message}}
function command(name){return async()=>{if(!confirm(`确认向设备发送 ${name}？`))return;try{$('command-result').textContent=JSON.stringify(await api('/api/pneumatic/command',{method:'POST',body:JSON.stringify({command:name})}),null,2)}catch(e){$('command-result').textContent=`失败：${e.message}`}}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active')});$('device-toggle').onclick=()=>{$('device-drawer').hidden=!$('device-drawer').hidden;if(!$('device-drawer').hidden)refreshPorts()};$('refresh-ports').onclick=refreshPorts;$('connect-port').onclick=async()=>{try{await api('/api/connect',{method:'POST',body:JSON.stringify({port:$('port-select').value})});poll()}catch(e){$('serial-detail').textContent=e.message}};$('disconnect-port').onclick=async()=>{await api('/api/disconnect',{method:'POST',body:'{}'});poll()};$('diagnostics-toggle').onclick=()=>$('diagnostics').showModal();document.querySelectorAll('[data-command]').forEach(b=>b.onclick=command(b.dataset.command));$('read-config').onclick=async e=>{e.preventDefault();try{const c=await api('/api/pneumatic/config');$('target-kpa').value=c.target_kpa;$('max-kpa').value=c.max_kpa;$('command-result').textContent=JSON.stringify(c,null,2)}catch(err){$('command-result').textContent=`失败：${err.message}`}};$('save-calibration').onclick=async e=>{e.preventDefault();if(!confirm('确认保存气动标定限制？'))return;try{$('command-result').textContent=JSON.stringify(await api('/api/pneumatic/command',{method:'POST',body:JSON.stringify({command:'save_calibration',target_kpa:Number($('target-kpa').value),max_kpa:Number($('max-kpa').value)})}),null,2)}catch(err){$('command-result').textContent=`失败：${err.message}`}};refreshPorts();poll();setInterval(poll,500);
